apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-deployment
  labels:
    app: app-book
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-book
  template:
    metadata:
      labels:
        app: app-book
    spec:
      containers:
        - name: app-book
          image: 076644905011.dkr.ecr.us-east-1.amazonaws.com/bookstore:latest
          imagePullPolicy: Always    
          ports:
            - containerPort: 5002