apiVersion: v1
kind: Service
metadata:
  name: book-app-service
spec:
  type: NodePort
  selector:
    app: app-book
  ports:
    - port: 5002
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 5002