apiVersion: apps/v1
kind: Deployment
metadata:
  name: autor-deployment
  labels:
    app: app-autor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-autor
  template:
    metadata:
      labels:
        app: app-autor
    spec:
      containers:
        - name: app-autor
          image: 076644905011.dkr.ecr.us-east-1.amazonaws.com/bookauthor:latest
          imagePullPolicy: Always    
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: ecr-registry-secret