apiVersion: v1
kind: Service
metadata:
  name: review-app-service
spec:
  type: NodePort
  selector:
    app: app-review
  ports:
    - port: 5001
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 5001